// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_qwBX4yY000-wpm4nu6QaGSvXLgr8Kno',
    appId: '1:671041841392:android:b0450c0332022df0877a35',
    messagingSenderId: '671041841392',
    projectId: 'teste-conexao-flutter',
    databaseURL: 'https://teste-conexao-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'teste-conexao-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZ8k4oPU1_jAO6z3Z-dTJmsC8o7PTBPXI',
    appId: '1:671041841392:ios:2ec3c6672ca2ecd3877a35',
    messagingSenderId: '671041841392',
    projectId: 'teste-conexao-flutter',
    databaseURL: 'https://teste-conexao-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'teste-conexao-flutter.appspot.com',
    iosClientId: '671041841392-dhfpecakba4krqq1c2fk89qq0s2vjnt9.apps.googleusercontent.com',
    iosBundleId: 'com.example.mapsFlutter',
  );
}
